# Generated by Django 4.2.30 on 2026-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_mgdl', models.IntegerField()),
                ('meal_context', models.CharField(default='General', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GlucoseReadings',
        ),
        migrations.RenameField(
            model_name='safetyrule',
            old_name='is_active',
            new_name='is_safe',
        ),
        migrations.RemoveField(
            model_name='safetyrule',
            name='description',
        ),
    ]
